version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crud123
      POSTGRES_DB: crudFeatureOne
    networks:
      - devnetwork
  test-db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crud123
      POSTGRES_DB: crudFeatureOneTest
    networks:
      - devnetwork
networks:
  devnetwork:
